# -*- coding: utf-8 -*-
"""Emlak lineer regresyon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LNUzqvq4-_VmjqJwIi8BuvIgJdLXAOLu
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import files
uploaded =files.upload()

USAhousing=pd.read_csv('USA_Housing.csv')
USAhousing.head()

sns.pairplot(USAhousing)

sns.displot(USAhousing['Price'])

USAhousing.corr()

from seaborn.matrix import heatmap
plt.figure(figsize=(6,6))
heatnap=sns.heatmap(USAhousing.corr(),vmin=-1,vmax=1,annot=True)
heatnap.set_title("Koralesyon",fontdict={'fontsize':12},pad=12)

x= USAhousing['Avg. Area Income'].values
y= USAhousing['Price'].values
print(x.shape)
print(type(x))

uzunluk=len(x)
x=x.reshape((uzunluk,1))
print(x.shape)
print(type(x))

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)

from sklearn.linear_model import LinearRegression
ln=LinearRegression()
ln.fit(x_train,y_train)

predictions=ln.predict(x_test)

sns.scatterplot(y_test,predictions)