# -*- coding: utf-8 -*-
"""Matplotlib

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xd18i8Iy7mMGjV0Sg4FQyKX6QoARMtIC
"""

from matplotlib import pyplot as plt

plt.plot([1,2,3], [4,5,1])
plt.show()

x = [5, 8 ,9]
y = [2,16, 7]
plt.plot(x,y)
plt.title("AKA Matplotlib Dersi")
plt.ylabel( "Y Ekseni")
plt.xlabel( "X Ekseni")
plt.show()

from matplotlib import  style

plt.bar([1, 2, 3, 4, 5 ], [50,40,70,80,20],  label = "Togg", width = .5)
plt.bar([1, 2, 3, 4, 5 ], [80,20,20,50,60],  label = "Tesla", color = 'r',width = .5)
plt.legend()
plt.title("(2025) En çok satan iki araç verileri")
plt.ylabel( "Satılan Kişi")
plt.xlabel( "Ay")
plt.show()

dilimler = [7,5,15,4]

aktiviteler = ["uyku", "yemek", "ders", "oyun"]
renkler = ["c","m", "r", "b"]

plt.pie(dilimler,
        labels = aktiviteler,
        colors = renkler,
        startangle = 90,
        shadow = True,
        explode = (0, 0.1,0 ,0),
        autopct = '%1.1f%%')
plt.title('Pasta Grafiği')
plt.show

